Updating RDoc Rake support
The following error occurs when you try to run `rake rdoc`:

```
rake aborted!
ERROR: 'rake/rdoctask' is obsolete and no longer supported. Use
'rdoc/task' (available in RDoc 2.4.2+) instead.
/Users/brooks/Desktop/gphoto4ruby/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
```

This commit resolves that issue by modifying the Rakefile to use the new
syntax.